galaxy_info:
  author: Zulfiya Zhumanazarova
  description: A simple role to install OpenJDK 
  company: Bosch
  license: MIT
  min_ansible_version: 2.4
  galaxy_tags: 
    - prerequisites
dependencies: []
 
